"""add served_at to formulas table

Revision ID: 78b549d02ccf
Revises: 02cf552a1854
Create Date: 2023-05-15 10:22:21.809608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78b549d02ccf"
down_revision = "02cf552a1854"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("formulas", sa.Column("served_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("formulas", "served_at")
    # ### end Alembic commands ###
