"""create formulas, instances, routes table

Revision ID: d4dfbfae2e9d
Revises: 
Create Date: 2023-05-04 17:36:07.413826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4dfbfae2e9d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "formulas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("creator", sa.String(length=32), nullable=False),
        sa.Column("author", sa.String(length=32), nullable=False),
        sa.Column("config", sa.Text(), nullable=False),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("creator", "slug", name="uq_formulas_creator_slug"),
    )
    op.create_index(op.f("ix_formulas_id"), "formulas", ["id"], unique=False)
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("route", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_id"), "routes", ["id"], unique=False)
    op.create_table(
        "instances",
        sa.Column("id", sa.String(length=5), nullable=False),
        sa.Column("formula_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["formula_id"],
            ["formulas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_instances_id"), "instances", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_instances_id"), table_name="instances")
    op.drop_table("instances")
    op.drop_index(op.f("ix_routes_id"), table_name="routes")
    op.drop_table("routes")
    op.drop_index(op.f("ix_formulas_id"), table_name="formulas")
    op.drop_table("formulas")
    # ### end Alembic commands ###
