"""add served_params to formulas table

Revision ID: f50947bd97b2
Revises: 78b549d02ccf
Create Date: 2023-08-21 15:26:46.241159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f50947bd97b2"
down_revision = "78b549d02ccf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("formulas", sa.Column("served_params", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("formulas", "served_params")
    # ### end Alembic commands ###
