#!/usr/bin/env sh

repo_root="$(git rev-parse --show-toplevel)"

cd "${repo_root}/ui" && ./.husky/pre-commit && cd "${repo_root}"
result1=$?

cd "${repo_root}/api" && ./.hooks/pre-commit && cd "${repo_root}"
result2=$?

if [ $result1 -ne 0 ] || [ $result2 -ne 0 ]; then
    exit 1
fi

exit 0
